package com.example.rdiandroiddevelopertest.model

data class ItemsMovie(val adult: Boolean?,
                      val backdropPath: String?,
                      val genreIDS: List<Long>?,
                      val id: Long?,
                      val originalLanguage: String?,
                      val originalTitle: String?,
                      val overview: String?,
                      val popularity: Double?,
                      val poster_path: String?,
                      val releaseDate: String?,
                      val title: String?,
                      val video: Boolean?,
                      val vote_average: Double?,
                      val vote_count: Long?,
                      val belongsToCollection: Any? = null,
                      val budget: Long?,
                      val genres: ArrayList<ItemsGenre>?,
                      val homepage: String?,
                      val imdbID: String?,
                      val productionCompanies: List<ProductionCompany>?,
                      val productionCountries: List<ProductionCountry>?,
                      val revenue: Long?,
                      val runtime: Long?,
                      val spokenLanguages: List<SpokenLanguage>?,
                      val status: String?,
                      val tagline: String?) {
}